eco-dessert-platform/backend

- src/main/java/com/bbangle/bbangle/token/controller/TokenApiController.java
- src/main/java/com/bbangle/bbangle/token/service/TokenService.java
프론트요청으로 변경사항이 500->200으로만 변경됐습니다
> 프론트 요청으로 토큰 유효성 통과 못해도 상태 200 처리

- src/test/java/com/bbangle/bbangle/AbstractIntegrationTest.java
- src/test/java/com/bbangle/bbangle/analytics/controller/AnalyticsControllerTest.java
- src/test/java/com/bbangle/bbangle/analytics/service/AnalyticsServiceTest.java
테스트 컴파일 오류가 나서 변경했습니다
리뷰 관련 변경이 좀 있었는데 반영이 안되서 수정했습니다!
변경 사항
- HARD -> DRY(프론트 명세와 맞추기 위해)
- Review 패키지 경로 변경
- Review 엔티티 내 뱃지 구분 타입 String -> Badge로 변경
> analytics 관련 테스트 리뷰 최신 사항으로 변경

- src/main/java/com/bbangle/bbangle/board/domain/Board.java
board에 status가 is_soldout으로 변경되면서 발생한 에러입니다
수정했습니다!
> 🐛 서버 구동 안되는 버그

- src/main/java/com/bbangle/bbangle/board/repository/basic/query/RecommendBoardQueryProviderResolver.java
board 조회 시 store에서 thumbnail을 가져오는 부분 해결
> thumbnail store 들어가는 부분 -> board로 변경

- src/main/java/com/bbangle/bbangle/analytics/controller/AnalyticsController.java
- src/main/java/com/bbangle/bbangle/analytics/dto/AnalyticsCreatedWithinPeriodResponseDto.java
- src/main/java/com/bbangle/bbangle/analytics/dto/AnalyticsCumulationResponseDto.java
- src/main/java/com/bbangle/bbangle/analytics/dto/AnalyticsMembersCountResponseDto.java
- src/main/java/com/bbangle/bbangle/analytics/dto/DateAndCountDto.java
- src/main/java/com/bbangle/bbangle/analytics/service/AnalyticsService.java
- src/main/java/com/bbangle/bbangle/config/WebOAuthSecurityConfig.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
**변경사항**
---
- WebOAuthSecurityConfig 파일에 (/api/v1/analytics/**).permitAll() 추가하여 인증문제 해결
- 스웨거 UI 태그, API명 명시
- 들여쓰기 수정
- 사용하지 않는 매서드 제거
> 관리자 통계 엔드포인트 시큐리티 필터체인 추가

- src/main/java/com/bbangle/bbangle/store/repository/StoreRepositoryImpl.java
> [기획팀 요청] 스토어 is_deleted true 일 때 조회 안되는 기능 추가

- .github/workflows/cd-pipeline-dev-aws.yml
- .gitignore
- src/main/java/com/bbangle/bbangle/config/SwaggerConfig.java
---
assignees: ''
---
- AWS로 이전, docker 기반의 spring 서버 운영으로 인해 새로운 CI/CD 파이프 라인이 필요
- yml 깃헙액션 시크릿 파일을 깃 프로젝트에 넣고 build 하는 과정까지는 동일
- 기존에 서버에 존재하는 jar 파일(이전 배포 버전에서 사용한 jar 파일 삭제)
- 새롭게 build한 jar 파일을 aws 서버로 이전
- spring server docker container 를 중지
- spring server docker image 삭제
- docker compose up server -d 명령어로 새롭게 받은 jar 파일을 기반으로 다시 서버 배포
```
|-- deploy-docker.sh
|-- docker/
|-- docker-compose.yml
|-- server/
|-- Dockerfile
|-- mysql/
|-- Dockerfile
|-- redis/
|-- data/
|-- conf/
|-- redis.conf
```
> AWS 환경에서 작동할 CI/CD 파이프 라인 추가

- src/main/java/com/bbangle/bbangle/board/repository/basic/query/MostWishedBoardQueryProviderResolver.java
---
assignees: ''
---
쿼리 많은 순으로 조회 시 sql 오류가 나오는 부분 확인 및 수정
> 리뷰 많은 순 쿼리 오류 수정

- src/main/java/com/bbangle/bbangle/board/repository/util/BoardPageGenerator.java
---
assignees: ''
---
isSoldout 컬럼이 null 인 경우 예외처리 추가
> isSoldout 컬럼이 null 인 경우 예외처리 추가

- src/main/java/com/bbangle/bbangle/member/repository/MemberRepository.java
- src/main/java/com/bbangle/bbangle/member/service/MemberService.java
- src/main/java/com/bbangle/bbangle/token/jwt/TokenProvider.java
- src/main/java/com/bbangle/bbangle/token/oauth/OauthService.java
- src/main/java/com/bbangle/bbangle/token/service/TokenService.java
- src/test/java/com/bbangle/bbangle/board/controller/BoardControllerTest.java
- src/test/java/com/bbangle/bbangle/board/repository/basic/cursor/CursorGeneratorTest.java
- src/test/java/com/bbangle/bbangle/board/repository/basic/query/BoardQueryProviderTest.java
- src/test/java/com/bbangle/bbangle/board/repository/folder/cursor/LowPriceCursorGeneratorTest.java
- src/test/java/com/bbangle/bbangle/board/repository/folder/cursor/PopularCursorGeneratorTest.java
- src/test/java/com/bbangle/bbangle/board/repository/folder/cursor/WishListRecentCursorGeneratorTest.java
- src/test/java/com/bbangle/bbangle/board/repository/folder/query/LowPriceBoardQueryProviderTest.java
- src/test/java/com/bbangle/bbangle/board/repository/folder/query/PopularBoardQueryProviderTest.java
- src/test/java/com/bbangle/bbangle/board/repository/folder/query/WishListRecentBoardQueryProviderTest.java
- src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
- src/test/java/com/bbangle/bbangle/configuration/TokenGenerator.java
- src/test/java/com/bbangle/bbangle/member/controller/MemberControllerTest.java
- src/test/java/com/bbangle/bbangle/member/service/MemberServiceTest.java
- src/test/java/com/bbangle/bbangle/preference/service/PreferenceServiceTest.java
- src/test/java/com/bbangle/bbangle/store/service/StoreServiceTest.java
- src/test/java/com/bbangle/bbangle/wishlist/controller/WishListStoreControllerTest.java
- src/test/java/com/bbangle/bbangle/wishlist/service/WishListBoardServiceTest.java
- src/test/java/com/bbangle/bbangle/wishlist/service/WishListFolderServiceTest.java
- 회원 탈퇴 시에도 로그인이 되는 버그 해결
- 회원 isDeleted 시 로그인 X
- 토큰 내에 email 삭제
> 🔧 토큰 내에 email 삭제 및 리팩토링 

- src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/service/BoardService.java
- src/main/resources/application.yml
---
assignees: ''
---
필터 조건 추가하면 board count 내려주는 api 추가
> Board count API 작성

- src/main/java/com/bbangle/bbangle/board/repository/BoardRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/store/dto/BoardsInStoreDto.java
- src/main/java/com/bbangle/bbangle/store/dto/BoardsInStoreResponse.java
- src/test/java/com/bbangle/bbangle/store/service/StoreServiceTest.java
> 🚀 스토어 상세페이지 리뷰 개수, 리뷰 평점 반환 구현

- src/main/java/com/bbangle/bbangle/exception/BbangleErrorCode.java
- src/main/java/com/bbangle/bbangle/review/controller/ReviewController.java
- src/main/java/com/bbangle/bbangle/review/dto/ReviewInfoResponse.java
- src/main/java/com/bbangle/bbangle/review/dto/ReviewSingleDto.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepository.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
- src/test/java/com/bbangle/bbangle/fixture/ReviewFixture.java
- src/test/java/com/bbangle/bbangle/review/service/ReviewServiceTest.java
---
about: 리뷰 수정 삭제 오류 해결 및 프론트 요청 처리
assignees: ''
---
- 작성자가 아니여도 리뷰 수정, 삭제가 가능했던 오류 해결
- [프론트 요청] 리뷰 조회 api 호출 시 로그인한 사용자가 리뷰 작성자인지 판단하는 api 스펙 추가
> 리뷰 수정 삭제 오류 해결 및 프론트 요청 처리

- src/main/java/com/bbangle/bbangle/search/dto/response/util/SearchPageGenerator.java
- src/main/java/com/bbangle/bbangle/search/service/SearchService.java
- src/test/java/com/bbangle/bbangle/search/repository/SearchRepositoryTest.java
- board All Count를 잘못 계산하고 있었음
- 테스트 에러 나는 것만 수정
> 🐛 테스트 코드 & 게시글 전체 개수 반환 에러 수정

- src/main/java/com/bbangle/bbangle/board/dto/BoardInfoDto.java
> 🔧 스토어 상세페이지 게시판 필드명 변경

- src/main/java/com/bbangle/bbangle/board/domain/Category.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/BoardFilterCreator.java
---
assignees: ''
---
- 빵과 과자 카테고리에 전체 보기가 추가됨에 따라 해당 카테고리 필터 로직 추가
- ALL_BREAD, ALL_SNACK 카테고리를 추가
- 해당 카테고리로 조회 시 category가 BREAD/SNACK 에 속한 카테고리 안에서 조회 되게 in 조건 추가
> 게시글 조회 시 카테고리에서 전체 빵, 전체 과자 카테고리 추가

- src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
- src/main/java/com/bbangle/bbangle/board/domain/Product.java
- src/main/java/com/bbangle/bbangle/board/dto/Nutrient.java
- src/main/java/com/bbangle/bbangle/board/dto/OrderAvailableDate.java
- src/main/java/com/bbangle/bbangle/board/dto/OrderAvailableWeek.java
- src/main/java/com/bbangle/bbangle/board/dto/OrderDateByUserDTO.java
- src/main/java/com/bbangle/bbangle/board/dto/OrderWeekByUserDTO.java
- src/main/java/com/bbangle/bbangle/board/dto/ProductOrderDto.java
- src/main/java/com/bbangle/bbangle/board/dto/ProductOrderResponse.java
- src/main/java/com/bbangle/bbangle/board/dto/ProductResponse.java
- src/main/java/com/bbangle/bbangle/board/repository/ProductQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/board/repository/ProductRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/service/BoardService.java
- src/main/java/com/bbangle/bbangle/push/domain/Push.java
- src/test/java/com/bbangle/bbangle/board/repository/BoardRepositoryTest.java
- src/test/java/com/bbangle/bbangle/board/repository/ProductRepositoryTest.java
- src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
- src/test/java/com/bbangle/bbangle/store/service/StoreServiceTest.java
- 빵켓팅 신청 했는지에 대한 필드가 없었음
- DATE, WEEK 에 따라 Response가 다름
- WEEK의 경우 
- DATE의 경우 
FixtureMonkey 너무너무 별로네요 ㅜㅜㅜㅜㅜ
> 🚀 빵켓팅 신청 여부 확인하는 필드 추가

- src/main/java/com/bbangle/bbangle/board/dto/BoardInfoDto.java
- boardstatistic에 review count int => bigint 형변환으로 인한 에러 발생
- 변경 완료
- 중간중간 fixture monkey로 인해 터지는 것들이 있는데, 조치가 필요해보여요
- entity의 abstract를 만들어 테스트 용, 런타임 용 두가지 만들어서 시도하면 좋을거 같아요
> review count를 int => long으로 변경

- .github/workflows/cd-pipeline-aws-deploy.yml
- .gitignore
---
assignees: ''
---
- 배포 서버 배포 완료
- main 브랜치에 머지될 때 작동할 파이프라인 추가
> main 배포 파이프라인 추가

- src/main/java/com/bbangle/bbangle/config/SwaggerConfig.java
> swagger fix dev

- src/main/java/com/bbangle/bbangle/config/SwaggerConfig.java
> fix swagger

- src/main/java/com/bbangle/bbangle/member/dto/ProfileInfoResponseDto.java
- src/main/java/com/bbangle/bbangle/member/service/ProfileServiceImpl.java
---
assignees: ''
---
- 전화번호 -> 성별로 내려주는 데이터 변경(기획)
> 프로필 내려주는 데이터 변경

- src/main/java/com/bbangle/bbangle/common/adaptor/slack/RealSlackAdaptor.java
- src/main/java/com/bbangle/bbangle/common/adaptor/slack/SlackMessage.java
- src/main/java/com/bbangle/bbangle/config/CorsConfig.java
> main < - dev

- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepository.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
---
assignees: ''
---
일부 리뷰 api에서 리뷰 삭제된 것도 나오는 현상 있어 조치
> 삭제된 리뷰 조회 안되도록 조치

- src/main/java/com/bbangle/bbangle/review/domain/Badge.java
- src/main/java/com/bbangle/bbangle/review/domain/Review.java
- src/test/java/com/bbangle/bbangle/DatabaseCleaner.java
---
assignees: ''
---
기존 맛, 질감, 당도 를 받는 Enum Class에 Null 값을 추가했습니다
스웨거 이상 없습니다
> gpt로 임의의 리뷰 insert 할 시 NULL 값 들어오는 경우 대비

- src/main/java/com/bbangle/bbangle/board/service/BoardService.java
---
assignees: ''
---
- DB에 "/BoardDetail/1/1.png"로 주소 저장
- 서버에서 "CDN주소" + "/BoardDetail/1/1.png" 결합해서 전달해야함
- 하지만 이전엔 "CDN주소/BoardDetail/1/1.png"를 DB에 넣어놨기에 결합 코드가 없음
- "/BoardDetail/1/1.png"프론트에 이렇게 주소가 내려감
- 에러
게다가 CDN 주소는 언제든 변경될 수 있다는 가정하에 수정에 용이하도록 CDN 주소를 DB에서 삭제했습니다.
에러코드
```
java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@59dae020 testClass = com.bbangle.bbangle.search.controller.SearchControllerTest, locations = [], classes = [com.bbangle.bbangle.BbangleApplication], contextInitializerClasses = [], activeProfiles = ["test"], propertySourceDescriptors = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContext …
```
> CDN 결합하여 URL 내려줌

- src/main/java/com/bbangle/bbangle/survey/collections/IsVegetarians.java
- src/main/java/com/bbangle/bbangle/survey/enums/IsVegetarian.java
---
assignees: ''
---
- 기존에 몸에 맞지 않는 성분과 채식 여부를 묻는 두 질문에서 '알'이라는 요소를 EGG로 사용
- 프론트 측에서 혼란을 야기할 것 같아 두 개의 명칭을 구분하자고 제안하여 수정
- IsVegitarain enum 의 `EGG` -> `ANIMAL_EGG`로 수정
- 해당 enum을 사용하는 모든 곳에서 수정
- enum만 변경, db의 컬럼은 기존 그대로 유지하는 방향으로 사용
> hotfix: 기피 식재료의 EGG와 구분하기 위해 채식 여부에서 IsVegitarian의 EGG를 ANIMAL_EGG로 변경

- src/main/java/com/bbangle/bbangle/image/repository/ImageRepository.java
- src/main/java/com/bbangle/bbangle/image/service/ImageService.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/review/scheduler/ReviewScheduler.java
- src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
- src/test/java/com/bbangle/bbangle/review/service/ReviewServiceTest.java
---
assignees: ''
---
1. dev s3 cdn 새로 생성으로 인해 
기존 cdn 붙이고 insert -> cdn 제거하고 insert로 변경 
기존 db에 저장된 데이터 그대로 select -> 데이터에 cdn 붙이고 select
로 변경했습니다
2. Transactional 어노테이션 스케줄러에 붙이지 않고 테스트 환경을 위해 각각 독립적으로 붙였습니다
3. 리뷰와 이미지 조회 시 정렬 방법 변경했습니다
> 리뷰 이미지 cdn 로직 수정 및 정렬 변경 

- src/main/java/com/bbangle/bbangle/board/service/RandomBoardService.java
---
assignees: ''
---
- 위시리스트 추가 여부가 반영되지 않는 문제 해결
> 위시리스트 들어있는지 여부 추가

- src/main/java/com/bbangle/bbangle/review/dto/ReviewDto.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
---
assignees: ''
---
**에러**
https://bbanggree.slack.com/archives/C06QV2G6N72/p1731842629134899
- No Construct 에러 발생
- 위 API에서 에러 발생하고 있는 것을 확인
**발생이유**
- Projections.constructor를 사용하고 있기에 
- 위 생성자를 사용하고 있지 않다고 표시
- 작성자도 코딩한 시간이 많이 지나서 긴가민가해서 코드리뷰 댓글을 반영해 삭제
- 문제 발생 
- Construct 로직 추가
```
public ReviewDto(Badge badgeTaste, Badge badgeBrix, Badge badgeTexture, BigDecimal rate) {
this.badgeTaste = badgeTaste;
this.badgeBrix = badgeBrix;
this.badgeTexture = badgeTexture;
this.rate = rate;
}
```
- Projections.constructor를 사용하는게 좋을까요 아니면 QClass를 사용하는게 좋을까요??
> 🐛상품 상세페이지 No Construct 에러 해결

- src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
- src/main/java/com/bbangle/bbangle/board/recommend/domain/MemberSegment.java
- src/main/java/com/bbangle/bbangle/board/recommend/domain/SegmentIntolerance.java
- src/main/java/com/bbangle/bbangle/board/recommend/enums/Segment.java
- src/main/java/com/bbangle/bbangle/board/recommend/repository/MemberSegmentRepository.java
- src/main/java/com/bbangle/bbangle/board/recommend/repository/RecommendBoardQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/board/recommend/repository/RecommendBoardQueryDSLRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/recommend/repository/RecommendBoardRepository.java
- src/main/java/com/bbangle/bbangle/board/recommend/service/RecommendBoardService.java
- src/main/java/com/bbangle/bbangle/board/service/BoardService.java
---
assignees: ''
---
- 데이터 팀 협업을 통한 메인화면 추천 시스템 정렬
- view 테이블의 멤버 별 기피재료 record 선택
- 각 기피재료에 해당하는 성분을 가진 product 필터링(product title 기반)
- 찜 순으로 정렬 순서 반영
> 메인 화면 추천 시스템 도입

- src/main/java/com/bbangle/bbangle/board/dto/BoardInfo.java
- src/main/java/com/bbangle/bbangle/board/dto/SimilarityBoardDto.java
- src/main/java/com/bbangle/bbangle/board/dto/SimilarityBoardResponse.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardDetailQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/service/BoardDetailService.java
- src/main/java/com/bbangle/bbangle/boardstatistic/repository/BoardPreferenceStatisticQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/boardstatistic/repository/BoardPreferenceStatisticRepository.java
- src/main/java/com/bbangle/bbangle/boardstatistic/repository/BoardPreferenceStatisticRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/boardstatistic/repository/BoardStatisticQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/boardstatistic/repository/BoardStatisticRepository.java
- src/main/java/com/bbangle/bbangle/boardstatistic/repository/BoardStatisticRepositoryImpl.java
- src/test/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryTest.java
- src/test/java/com/bbangle/bbangle/board/service/BoardDetailServiceTest.java
- src/test/java/com/bbangle/bbangle/fixture/ProductFixture.java
- src/test/java/com/bbangle/bbangle/fixture/RecommendationSimilarBoardFixture.java
---
assignees: ''
---
https://github.com/eco-dessert-platform/backend/issues/313
**변경전**
- RecommendationSimilarityBoard 테이블에서 추천 상품 정보 가져옴
- 모든 게시물 추천 상품 다 들어있음
- Response로 반환
**변경후**
- SoldOut으로 인해 상품 추천을 3개 이하로 해줘야 하는 경우 30등 안에 드는 인기 게시글 랜덤으로 상품 추천에 추가
- 추천 상품이 없는 경우에도 30등 안에 드는 인기 게시글 랜덤으로 상품 추천에 추가
- 빠르게 구현해야해서 감안하고 봐주시길 부탁드립니다
> ✅ 상품 추천 로직 변경 완료

- src/main/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryImpl.java
---
assignees: ''
---
- isWished가 true가 아니라면 Join으로 인해 데이터 제거
- 위시리스트에 등록이 안돼있으면 데이터를 안가져옴
- join -> leftJoin 변경
> 🐛 Wished가 true가 아니면 손실되던 에러 해결

- build.gradle
- src/main/java/com/bbangle/bbangle/board/domain/Board.java
- src/main/java/com/bbangle/bbangle/config/SwaggerConfig.java
- src/main/java/com/bbangle/bbangle/member/domain/Member.java
- src/main/java/com/bbangle/bbangle/member/repository/SignatureAgreementRepository.java
- src/test/java/com/bbangle/bbangle/fixturemonkey/FixtureMonkeyConfig.java
- src/test/java/com/bbangle/bbangle/fixturemonkey/FixtureMonkeyTest.java
- src/test/java/com/bbangle/bbangle/fixturemonkey/ListContainerPropertyGenerator.java
- src/test/java/com/bbangle/bbangle/member/service/MemberServiceTest.java
- src/test/java/com/bbangle/bbangle/review/service/ReviewServiceTest.java
노션 링크로 첨부하겠습니다!
https://invented-streetcar-5cd.notion.site/Fixture-Monkey-144d70faa06880f588abdcc7e3290bfd?pvs=4
> fixturemonkey 전역설정

- .github/workflows/cd-pipeline-aws-deploy.yml
- .github/workflows/cd-pipeline-dev-aws.yml
1. 메인 CI/CD
- 쉘 스크립트 이름 변경
2. 개발 CI/CD
- 같은 서버에서 돌리므로 시크릿 키 수정
> 🔧 cicd 코드 수정

- src/main/java/com/bbangle/bbangle/board/domain/Nutrition.java
- src/main/java/com/bbangle/bbangle/board/repository/ProductRepository.java
- src/main/java/com/bbangle/bbangle/config/CorsConfig.java
- src/main/java/com/bbangle/bbangle/config/WebOAuthSecurityConfig.java
DB에서는 servingWeight로 돼있고, 서버는 servingSize로 돼 있어 에러 발생
> 🚒 상세페이지 상품 조회 API 에러 긴급 수정

- src/main/java/com/bbangle/bbangle/common/service/RequestTimeInterceptor.java
- src/main/java/com/bbangle/bbangle/config/WebConfig.java
1. 전체 컨트롤러 API 요청 시간 ~ 끝나는 시간 속도 측정
> 서버 속도 저하로 인해 속도 측정할 수 있는 클래스 구현

- src/main/java/com/bbangle/bbangle/common/service/RequestTimeInterceptor.java
- 서버 속도가 너무 느려 어떤 API인지 확인 후 개선하고자 구현함
> 🔥 3초 이상 소요되는 API 슬랙으로 전송 구현

- src/main/java/com/bbangle/bbangle/common/adaptor/slack/DevelopSlackAdaptor.java
- src/main/java/com/bbangle/bbangle/common/adaptor/slack/LocalSlackAdaptor.java
- src/main/java/com/bbangle/bbangle/common/adaptor/slack/SlackAdaptor.java
- src/main/java/com/bbangle/bbangle/common/adaptor/slack/SlackMessage.java
- src/main/java/com/bbangle/bbangle/common/service/RequestTimeInterceptor.java
- src/main/java/com/bbangle/bbangle/config/SwaggerConfig.java
- 3초 이상 걸리는 API 표시
- 기존엔 슬랙 안울림
- 울림으로 표시
> [Feat] 개발서버 스웨거 알림 구현

- src/main/java/com/bbangle/bbangle/image/controller/ImageController.java
> [Feat] 보드 디테일 이미지 저장 api 구현

- src/main/java/com/bbangle/bbangle/common/page/CursorPageResponse.java
> [Fix] CursorPageResponse 클래스 Redis 직렬화 에러

- src/main/resources/flyway/V10__app.sql
- src/main/resources/flyway/V11__app.sql
- src/main/resources/flyway/V12__app.sql
- src/main/resources/flyway/V13__app.sql
- src/main/resources/flyway/V14__app.sql
- src/main/resources/flyway/V1_app.sql
- src/main/resources/flyway/V2_app.sql
- src/main/resources/flyway/V3_app.sql
- src/main/resources/flyway/V5__app.sql
- src/main/resources/flyway/V6__app.sql
- src/main/resources/flyway/V7__app.sql
- src/main/resources/flyway/V8__app.sql
- src/main/resources/flyway/V9__app.sql
1. Flyway를 로컬에서 사용하지만, 개발 서버, 프로덕트 서버에서 사용안함
- 버전과 서버가 동기화 돼야하는데 그렇지 못했기 때문에 수동으로 마이그레이션 진행했음
2. 편의를 위해 도입했지만, 불편해지는 상황이 발생
3. 이를 개선하기 위해 docker-compose 파일 수정 및 Flyway 패키지 생성 후 관리
> Flyway 버전 관리 폴더 생성

- encode-applications.ps1
1. 매번 Base64로 인코딩해주는 코드 작성하기 귀찮음
2. PowerShell 스크립트를 만들어서 문제 해결
**사용방법**
- backend 루트(최상위)에서 터미널에  "./파일명" 입력 // ex) ./encode-applications.ps1
- src/main/resources/ 경로에 [].base.txt 파일 생성 됨
> [Feat] Base64로 인코딩해주는 프로그램 구현

- src/test/java/com/bbangle/bbangle/search/service/SearchServiceMockTest.java
> [Fix] 테스트 코드 컴파일 에러

- src/main/java/com/bbangle/bbangle/exception/GlobalControllerAdvice.java
> [Feat] 예외 발생 시 Stack Trace 로그 추가

- src/main/java/com/bbangle/bbangle/board/controller/StoreController.java
- src/main/java/com/bbangle/bbangle/board/facade/StoreFacade.java
- src/main/java/com/bbangle/bbangle/board/service/StoreService.java
- src/main/java/com/bbangle/bbangle/board/service/dto/StoreInfo.java
- src/main/java/com/bbangle/bbangle/board/service/mapper/StoreInfoMapper.java
> 스토어 게시물 조회 무한스크롤 추가

- src/main/java/com/bbangle/bbangle/analytics/controller/AnalyticsController.java
- src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
- src/main/java/com/bbangle/bbangle/board/controller/BoardDetailController.java
- src/main/java/com/bbangle/bbangle/board/controller/ProductImgController.java
- src/main/java/com/bbangle/bbangle/board/controller/RandomBoardController.java
- src/main/java/com/bbangle/bbangle/board/controller/StoreController.java
- src/main/java/com/bbangle/bbangle/common/dto/SingleResult.java
- src/main/java/com/bbangle/bbangle/image/controller/ImageController.java
- src/main/java/com/bbangle/bbangle/member/controller/MemberController.java
- src/main/java/com/bbangle/bbangle/member/controller/ProfileController.java
- src/main/java/com/bbangle/bbangle/notification/controller/NotificationController.java
- src/main/java/com/bbangle/bbangle/preference/controller/PreferenceController.java
- src/main/java/com/bbangle/bbangle/push/controller/PushController.java
- src/main/java/com/bbangle/bbangle/review/controller/ReviewController.java
- src/main/java/com/bbangle/bbangle/search/controller/SearchController.java
- src/main/java/com/bbangle/bbangle/survey/controller/SurveyController.java
- src/main/java/com/bbangle/bbangle/token/controller/TokenApiController.java
- src/main/java/com/bbangle/bbangle/wishlist/controller/WishListBoardController.java
- src/main/java/com/bbangle/bbangle/wishlist/controller/WishListFolderController.java
- src/main/java/com/bbangle/bbangle/wishlist/controller/WishListStoreController.java
1. @Schema(example=)로 응답값 고정됨
2. 모든 API 리턴값이 CommonResult로 스웨거가 정확한 DTO 데이터 구조를 모름
- @Schema(example=) 삭제
- CommonResult -> SingleResult<AnalyticsMembersCountResponseDto> 와 같이
> [Fix] Swagger 200 응답에서 데이터 구조 보이게 

- .github/workflows/cd-pipeline-aws-deploy.yml
> [Refactor] CICD 수정

- src/main/resources/flyway/V19__app.sql
1. 프론트 요청에 따라 ```<html><body></body></html> => <div></div>``` 로 변경
> board_detail 테이블 content컬럼 데이터 수정
