- src/main/java/com/bbangle/bbangle/board/repository/basic/cursor/RecommendCursorGenerator.java
스토어와 동일 합니다. 
상품 게시글이 필터가 추천순일때만 추가했습니다
> [기획팀 요청] 상품게시글 is_deleted true 일 때 조회 안되는 기능 추가

- build.gradle
- resource/mariadb/init.sql
- src/main/java/com/bbangle/bbangle/config/FirebaseConfig.java
- src/main/java/com/bbangle/bbangle/config/WebOAuthSecurityConfig.java
- src/main/java/com/bbangle/bbangle/exception/BbangleErrorCode.java
- src/main/java/com/bbangle/bbangle/push/controller/PushController.java
- src/main/java/com/bbangle/bbangle/push/domain/Push.java
- src/main/java/com/bbangle/bbangle/push/domain/PushCategory.java
- src/main/java/com/bbangle/bbangle/push/dto/CreatePushRequest.java
- src/main/java/com/bbangle/bbangle/push/dto/PushMessage.java
- src/main/java/com/bbangle/bbangle/push/dto/PushRequest.java
- src/main/java/com/bbangle/bbangle/push/dto/PushResponse.java
- src/main/java/com/bbangle/bbangle/push/dto/SendPushRequest.java
- src/main/java/com/bbangle/bbangle/push/repository/PushQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/push/repository/PushQueryDSLRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/push/repository/PushRepository.java
- src/main/java/com/bbangle/bbangle/push/service/FcmService.java
- src/main/java/com/bbangle/bbangle/push/service/PushService.java
- src/test/java/com/bbangle/bbangle/AbstractIntegrationTest.java
- src/test/java/com/bbangle/bbangle/DatabaseCleaner.java
- src/test/java/com/bbangle/bbangle/fixture/PushFixture.java
- src/test/java/com/bbangle/bbangle/push/controller/PushControllerTest.java
- src/test/java/com/bbangle/bbangle/push/service/PushServiceTest.java
---
about: 푸시 알림 기능 1차 구현
---
Issues [#140](https://github.com/eco-dessert-platform/backend/issues/140)
- Push 엔티티 생성
- 푸시 등록(재등록), 해제, 삭제, 조회 기능 구현
- 실제로 사용자에게 푸시 알림 나가는 기능은 구현되지 않은 상태이지만 프론트팀 요청으로 1차 merge
- 기능 미구현으로 FirebaseConfig 비활성화
- CRUD만 정상 동작
> 푸시 알림 기능 1차 구현

- src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/BoardFilterCreator.java
- src/test/java/com/bbangle/bbangle/board/repository/basic/cursor/CursorGeneratorTest.java
- src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
---
assignees: ''
---
*Resolves #198 
- FilterCreator에 금일 주문 가능 조건이 들어갈 경우 우선 오늘에 해당하는 요일을 찾는다
- 예를들어 오늘이 일요일이면 LocalDate.now().getDayOfWeek();로 일요일을 찾아서 변수로 선언
- switch case로 builder.and(product.sunday.eq(true)); 조건을 찾아 where 조건문에 넣을 수 있도록 BooleanBuilder에 추가
- 요일마다 분기문처리가 되어 상품 중 그 요일에 주문이 가능한 상품을 필터링할 때 사용됨
- 해당 조건으로 board 조회
- 실제 테스트 결과로 5개의 product에 sunday 컬럼에 1 값(true)를 넣어주고 테스트
- 오늘 주문 가능 상품만 조회 시 정상적으로 해당 product를 가지고 있는 board만 조회가 됨을 확인
- test 깨지는 현상(board의 isDeleted가 조회 조건문에 추가됨으로 발생한) 수정
> 오늘 주문 가능 상품 필터 조건 리팩토링

- src/main/java/com/bbangle/bbangle/image/repository/ImageRepository.java
- src/main/java/com/bbangle/bbangle/image/service/ImageService.java
- src/main/java/com/bbangle/bbangle/image/service/S3Service.java
- src/main/java/com/bbangle/bbangle/review/domain/Review.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
---
about: 리뷰 수정 시 이미지 처리 로직 리팩토링
assignees: 윤동석
---
#200 
리뷰 수정 시 이미지 처리 로직을 리팩토링 했습니다
변경 사항은 이슈에 자세히 적어 놓았으니 확인해주시면 감사하겠습니다
S3 를 확인하는게 핵심이였기 때문에 스웨거로 테스트 진행했습니다
추후 테스트 코드까지 추가하겠습니다
테스트 로직 설명
이미지 업로드 API로 이미지 4개 추가 -> 리뷰 작성 -> 이미지 1개 추가 -> 리뷰 수정 
1. 이미지 업로드 API로 이미지 4개 추가
해당 로직 수행으로 S3에 review/-1 에 임시로 이미지 저장
2. 리뷰 작성
S3 review/{reviewId} 폴더에 이미지 담기는 것 확인
3. 리뷰 수정 시 사용자가 새로 이미지 1개를 추가했다고 가정
4. 리뷰 수정
테스트 상황
기존 이미지 4개 중 2개는 삭제, 1개는 유지, 3번 단계에서 추가한 이미지 1개를 추가한다고 가정
S3 테스트 결과
해당 리뷰 DB  조회
> [프론트 요청] 리뷰 수정 시 이미지 처리 로직 리팩토링

- src/main/java/com/bbangle/bbangle/image/repository/ImageRepository.java
- src/main/java/com/bbangle/bbangle/image/service/ImageService.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewLikeRepository.java
- src/main/java/com/bbangle/bbangle/review/scheduler/SchedulerFactory.java
- src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
- src/test/java/com/bbangle/bbangle/review/BestReviewSchedulerTest.java
- src/test/java/com/bbangle/bbangle/review/service/ReviewServiceTest.java
---
about: 리뷰 삭제 리팩토링 및 이미지 삭제 스케줄러 추가
assignees: ''
---
Resolves #201 
- 이미지 업로드만 되고 리뷰 작성에 사용되지 않은 이미지들 삭제하는 스케줄러 추가
- 리뷰 삭제 시 연관된 이미지와 좋아요 deleteAll로 처리했으나 Spring data JPA가 단건으로 처리한다는 이슈가 있어 
일괄 처리로 변경
- 리뷰 없는 게시글 조회 및 유저가 리뷰를 작성하지 않은 경우 내가 작성한 리뷰 조회 할 시 나타나는 에러 처리
전체 테스트
리뷰 삭제 테스트 시 이미지와 좋아요 delete 쿼리 확인
리뷰 없는 게시글 조회
> 리뷰 삭제 리팩토링 및 이미지 삭제 스케줄러 추가

- src/main/java/com/bbangle/bbangle/config/OctetStreamReadMsgConverter.java
- src/main/java/com/bbangle/bbangle/config/WebConfig.java
- src/main/java/com/bbangle/bbangle/member/controller/MemberController.java
- src/main/java/com/bbangle/bbangle/member/dto/MemberAssignResponse.java
- src/main/java/com/bbangle/bbangle/member/repository/SignatureAgreementRepository.java
- src/main/java/com/bbangle/bbangle/member/service/MemberService.java
- src/test/java/com/bbangle/bbangle/member/controller/MemberControllerTest.java
- src/test/java/com/bbangle/bbangle/member/service/MemberServiceTest.java
---
assignees: ''
---
* Resolves #205 
- 프론트에서 사용자가 완전히 가입을 완료했는지, 취향을 선택했는지를 기준으로 보는 페이지가 달라져 이를 확인할 수 있는 api 추가
- 유저의 동의항목이 정상적으로 DB에 저장되어 있는지 여부로 확인
- 유저의 취향 선택이 정상적으로 DB에 저장되어 있는지 여부로 확인
- 테스트 중 유저 정보 업데이트 과정에서 프로필과 추가정보를 함께 업데이트하는 api(/api/v1/members/additional-information)가 스웨거에서 오류가 나는 것을 확인하고 HttpConvertor 설정을 추가해서 작동하도록 변경
- 각각 케이스별 테스트 케이스 테스트 및 스웨거 화면 추가
- 취향만 등록된 경우
- 동의만 한 경우 
- 둘 다 안된 경우 
- 둘 다 된 경우 등
> 유저의 정보를 내려주는 기능 추가

- resource/mariadb/init.sql
- src/main/java/com/bbangle/bbangle/board/service/BoardService.java
- src/main/java/com/bbangle/bbangle/exception/BbangleErrorCode.java
- src/main/java/com/bbangle/bbangle/page/SearchCustomPage.java
- src/main/java/com/bbangle/bbangle/search/controller/SearchController.java
- src/main/java/com/bbangle/bbangle/search/domain/Search.java
- src/main/java/com/bbangle/bbangle/search/dto/KeywordDto.java
- src/main/java/com/bbangle/bbangle/search/dto/response/RecencySearchResponse.java
- src/main/java/com/bbangle/bbangle/search/dto/response/SearchResponse.java
- src/main/java/com/bbangle/bbangle/search/repository/SearchQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/search/repository/SearchRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/search/repository/basic/query/SearchMostWishedBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/search/repository/basic/query/SearchRecentBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/search/service/SearchLoadService.java
- src/main/java/com/bbangle/bbangle/search/service/SearchService.java
- src/main/java/com/bbangle/bbangle/search/service/utils/KeywordUtil.java
- src/main/java/com/bbangle/bbangle/search/validation/SearchValidation.java
- src/test/java/com/bbangle/bbangle/fixture/FixtureConfig.java
- src/test/java/com/bbangle/bbangle/fixture/ProductFixture.java
- src/test/java/com/bbangle/bbangle/fixture/SearchFixture.java
- src/test/java/com/bbangle/bbangle/search/controller/SearchControllerTest.java
- src/test/java/com/bbangle/bbangle/search/repository/SearchRepositoryTest.java
- src/test/java/com/bbangle/bbangle/search/service/SearchServiceMockTest.java
- src/test/java/com/bbangle/bbangle/search/service/SearchServiceTest.java
https://github.com/eco-dessert-platform/backend/issues/188
- 로직은 변화없이 리팩토링 했습니다
- 검색어 저장
- 회원일 경우 검색어 저장
- 비회원일 경우 멤버 아이디 1L로 검색어 저장
- 인기 검색어 캐싱 & 조회
- 현재 시간부터 24시간 전 검색어를 통계내서 레디스에 7개 캐싱
- 조회 시 캐싱한 데이터 7개 반환
- 최근 검색어 조회 & 삭제
- 회원일 경우 최근 검색한 검색어 7개를 내려줌
- 중복 검색어 제외 7개
- 검색어 삭제 시 isDeleted True로 활성화 
- 검색 결과
- 테스트 시 에러 발견
- board_statistics이 SearchMostWishedBoardQueryProviderResolver.java클래스에서 Join이 빠져있음
- 검색 성능이 완전 좋은 것 같지 않아요.. "비건베이커리"와 "비건 베이커리"를 각각 {"비","건","베이커리"}, {"비건", "베이커리"} 이렇게 인식하더라구요. 더 좋은 토큰화 모델 있거나 개선사항이 있다면 의견 부탁드릴게요!!
> 🔧 검색 부수 기능 리팩토링

- src/main/java/com/bbangle/bbangle/search/service/utils/KeywordUtil.java
베스트키워드 스케줄러 업데이트 시 삭제되는 코드 추가
- 아래 이미지처럼 베스트 키워드가 계속 쌓임
- 한시간에 한번씩 업데이트를 하는데 기존 키워드를 삭제안하고 지속적으로 추가해서 생기는 문제
> 🐛 베스트 키워드 계속 쌓이는 문제 해결

- src/main/java/com/bbangle/bbangle/member/domain/Member.java
- src/test/java/com/bbangle/bbangle/fixture/MemberFixture.java
- src/test/java/com/bbangle/bbangle/member/service/MemberServiceTest.java
- src/test/java/com/bbangle/bbangle/search/service/SearchServiceMockTest.java
---
assignees: ''
---
- 카카오 로그인으로 정보를 받아온 후 해당 멤버가 DB에 존재하는지 확인하기 위해 provider(social login 제공처), providerId(식별자)로 구분함
- 그러나 providerId를 삭제 시 같이 변경해주지 않아 다시 가입하더라도 아직 존재하는 멤버처럼 조회하는 문제 발생
- providerId 정보를 다른 개인정보와 함께 '-' 처리해주는 방식으로 변경
- 같은 정보로 다시 회원 가입 시 정상적으로 가입됨을 확인
- 이로 인해 보이지 않던 폴더와 찜하기 기능도 다시 활성화
> 유저 삭제 후 제 가입 시 제대로 삭제되지 않는 문제 해결

- src/main/java/com/bbangle/bbangle/config/CorsConfig.java
- src/main/java/com/bbangle/bbangle/push/domain/Push.java
- src/main/java/com/bbangle/bbangle/push/domain/PushCategory.java
- src/main/java/com/bbangle/bbangle/push/dto/CreatePushRequest.java
- src/main/java/com/bbangle/bbangle/push/dto/FcmMessageDto.java
- src/main/java/com/bbangle/bbangle/push/dto/FcmPush.java
- src/main/java/com/bbangle/bbangle/push/repository/PushQueryDSLRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/push/service/FcmService.java
- src/main/java/com/bbangle/bbangle/push/service/PushService.java
- src/main/java/com/bbangle/bbangle/review/scheduler/ReviewScheduler.java
- src/main/java/com/bbangle/bbangle/store/repository/StoreRepositoryImpl.java
- src/test/java/com/bbangle/bbangle/fixture/ProductFixture.java
- src/test/java/com/bbangle/bbangle/fixture/PushFixture.java
- src/test/java/com/bbangle/bbangle/push/service/PushServiceTest.java
---
assignees: ''
---
Closes #140 
- FCM 날짜별 알림 기능 구현
- [프론트 요청] 스토어 개별 조회 시 찜 유무 조회 오류
생각보다 FCM에서 알림 보내는 게 느린데 restTemplate 대안으로 나온 webClient가 있더라구요.
예상보다 빠르게 도입해야 될지도 모르겠습니다
> FCM 날짜별 알림 기능 구현

- src/main/java/com/bbangle/bbangle/board/service/BoardService.java
- src/main/java/com/bbangle/bbangle/wishlist/controller/WishListBoardController.java
---
assignees: ''
---
- 위시리스트 폴더에 있는 board임에도 board 전체 조회 시 isWished : false 로 나오는 에러 해결
로직의 문제보다 Sprinfg data JPA 의 exist 를 사용하여 만든 쿼리의 매개변수 순서가 문제였음
이번일을 통해 테스트 코드에서 이를 잡아내지 못함은 
어떻게 테스트 코드를 짜야하는 가에 대해서 한번 생각해볼 만 문제라고 생각함
**추가 논의 사항
Board와 Product, ProductIImg가 여전히 @OneToMany @ManyToOne 을 사용중이여서 
엔티티 수정 및 쿼리 수정도 추후 리팩토링 시에 필요해 보임
> 위시리스트 폴더에 있는 board임에도 board 전체 조회 시 isWished : false 로 나오는 에러 해결

- src/main/java/com/bbangle/bbangle/board/repository/BoardQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/cursor/PreferenceRecommendCursorGenerator.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/query/PreferenceRecommendBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/board/service/BoardService.java
---
assignees: ''
---
- 로그인 한 사람의 경우 그 사람의 취향을 조회한다
- 선호도 추천 테이블에서 조회한 취향으로 필터링 
- 필터링 후 커서기반 페이지네이션을 적용
조회 쿼리
```sql
Hibernate: 
select
p1_0.id,
p1_0.preference_type 
from
preference p1_0 
join
member_preference mp1_0 
on p1_0.id=mp1_0.preference_id 
where
mp1_0.member_id=?
Hibernate: 
select
distinct b1_0.id 
from
product p1_0 
join
product_board b1_0 
on p1_0.product_board_id=b1_0.id 
join
board_preference_statistic bps1_0 
on bps1_0.board_id=b1_0.id 
where
b1_0.is_deleted=? 
and bps1_0.preference_type=? 
order by
bps1_0.preference_score desc 
limit
?
Hibernate: 
select
b1_0.id,
s1_0.id,
s1_0.name,
b1_0.profile,
b1_0.title,
b1_0.price,
p1_0.category,
p1_0.gluten_free_tag,
p1_0.high_protein_tag, …
```
> 추천순 선택 시 취향 가중치 반영 조회 로직 수정

- src/main/java/com/bbangle/bbangle/board/repository/ProductQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/board/repository/ProductRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/push/dto/CreatePushRequest.java
- src/main/java/com/bbangle/bbangle/push/dto/FcmRequest.java
- src/main/java/com/bbangle/bbangle/push/service/PushService.java
- src/main/java/com/bbangle/bbangle/token/oauth/OauthService.java
- src/test/java/com/bbangle/bbangle/push/service/PushServiceTest.java
---
assignees: ''
---
[프론트 요청] 재입고 및 빵켓팅 알림 재신청시 pushType이 null 이여도 처리
- 재입고는 날짜별, 요일별 알림이 없기 때문에 프론트에서 보낼 필요가 없다는 의견
- 이에 따라 RequestDto의 pushType 을 null 처리
- 빵켓팅 / 재입고 조회 페이지에서 빵켓팅 재신청시 프론트에서 해당 상품이 날짜별, 요일별 알림 유무를 판단할 수 없다는 의견
- API에 요일이 포함되어 있으면 요일만 업데이트 하는 것으로 변경
> [프론트 요청]재입고 및 빵켓팅 알림 재신청시 pushType이 null 이여도 처리

- .github/workflows/cd-pipeline-aws-deploy.yml
---
name: "✅ bug"
title: "✅ bug"
labels: ✅ bug
assignees: ''
---
Close #255 
- main 서버에 코드를 merge 시켜도 Production 서버에 도커가 업데이트가 안 되는 오류가 발생했습니다.
- 원인은 production github Action 파일에서 도커 빌드 빌드 주체가 DEPLOY_AWS_SSH_HOST 가 아니라 DEV_AWS_SSH_HOST로 되어있었습니다.
- 즉, 최신 jar파일은 운영서버에 넘겨주고 개발서버에 jar파일을 도커 빌드 한 게 문제였습니다. 
- 단순하게 변수명 수정해주었습니다
> production deploy 변수 실수 수정

- src/main/java/com/bbangle/bbangle/config/SwaggerConfig.java
---
assignees: ''
---
로컬에서 테스트 할때는 이렇게 나옵니다
다만 이렇게 나오려면
이 설정도 필요한데
이 대화로 인해 다른 거 건드릴 필요 없이 Swagger Config 파일에 profile만 설정했고
application-production.yml이 어떻게 설정되어 있는지 몰라 건드리지 못했습니다
또한 저희 운영 쪽 서버이기 때문에 swagger 접속은 안 할 것으로 예상됩니다.
제 생각이 틀리다면 코멘트 주세요!
> 운영환경에서 swagger 사용 안되게 조치

- src/main/java/com/bbangle/bbangle/common/adaptor/slack/RealSlackAdaptor.java
- src/main/java/com/bbangle/bbangle/common/adaptor/slack/SlackMessage.java
---
- 에러 길이가 길 시 badRequest로 슬랙 전송이 안됐습니다
- 코드 정리( 클래스 분리)
- 글자 수 제한(header는 150자, section은 3000자)
> 슬랙 에러 글자 수 제한 추가

- src/main/java/com/bbangle/bbangle/board/dto/BoardImageDetailResponse.java
- src/main/java/com/bbangle/bbangle/board/service/BoardService.java
- src/main/java/com/bbangle/bbangle/exception/BbangleErrorCode.java
- src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
- 동석님께서 DB에 이미지 URL에 붙어있는 CDN 제거
- Board Profile에 CDN URL도 삭제됨
- 그것을 해결하기 위해 Product에 CDN 동적 생성 코드 추가
+ BoardImage에도 CDN 추가
아래 이미지 문제 해결하기 위해 개발 시작함
기존  = "profile": "product_board/4/9782392925/profile.png"
변경 = "profile": "https://d41zmgwrjn4bn.cloudfront.net/product_board/4/9782392925/profile.png",
리뷰 업로드는 yml 설정이 잘못돼 나는 에러이고, 나머지 Review 에러는 FixtureMonkey로 인해 발생하는 에러입니다.
매번 돌릴 때 마다 합격 불합격이 나뉘더라구요
이미지가 많아질 수록 이미지 관련 로직이 추가될 때마다 개발이 힘들어질텐데, 공통화 작업을 어떻게 진행할지 고민
> Board Profile CDN 추가

- src/main/java/com/bbangle/bbangle/member/controller/ProfileController.java
- src/main/java/com/bbangle/bbangle/member/domain/Member.java
- src/main/java/com/bbangle/bbangle/member/dto/InfoUpdateRequest.java
---
assignees: ''
---
- 프론트 요청으로 인한 업데이트 진행
- 전화번호 -> 성별로 프로필 업데이트 변경
- 내부 Dto, update 로직을 전화번호에서 성별 변경으로 바꿈
- 스웨거에 MultipartFile과 RequestDto 구분될 수 있게 컨트롤러 옵션 변경
정상 작동 확인(스웨거)
> profile 업데이트 메서드에서 전화번호 대신 성별 노출

- src/main/java/com/bbangle/bbangle/BbangleApplication.java
- src/main/java/com/bbangle/bbangle/board/dto/BoardResponseDto.java
- src/main/java/com/bbangle/bbangle/board/repository/util/BoardPageGenerator.java
- src/main/java/com/bbangle/bbangle/board/service/BoardService.java
- src/main/java/com/bbangle/bbangle/boardstatistic/ranking/UpdateBoardStatistic.java
- src/main/java/com/bbangle/bbangle/config/RedisCacheConfig.java
- src/main/java/com/bbangle/bbangle/page/BoardCustomPage.java
- src/main/java/com/bbangle/bbangle/page/CustomPage.java
---
assignees: ''
---
- 과거 힙메모리가 터지는 이슈가 있었음
- 성능 테스트 중 가장 빈번하게 호출되는 요청에 대해 (/api/v1/boards) 성능 확인 후 캐싱 적용 필요 확인
- 게시글 조회 시 추출한 데이터를 정재하기 위해 LinkedHashMap이 다수 사용되는 것을 확인
- LinkedHashMap은 서로 참조가 강하게 묶여있어 GC로 잘 사라지지 않는 객체이다.
- 사용이 끝난 LinkedHashMap에 대하여 map.clear()메서드를 사용하여 그 즉시 객체를 비워줌
- 부하테스트 후 남아있던 LinkedHashmap 객체가 사라짐을 확인 가능
before(약 10분간 LinkedHashMap 객체가 Heap 영역에 남아있음을 확인)
After(부하테스트 요청 후 바로 객체가 사라짐을 확인)
- api/v1/boards 는 페이지에 접속하면 나타나는 요청으로 가장 빈번히 호출되는 요청(비로그인 추천순 게시글 보내기 요청)
- 트래픽이 몰릴 시 가장 많이 호출되는 api다
캐싱 적용 전
캐싱 적용 후
성능 약 10배 이상 향상 확인
- 1시간 마다 랭킹 업데이트 시 정렬 순서가 같이 업데이트 되게 설정
- 업데이트가 시작될 때 키가 사라지고 다시 같은 요청을 날리면 캐시에 들어가는 걸 확인
* 업데이트가 안되는 경우를 위해 캐싱 시간을 30분으로 설정(랭킹 업데이트 시 CacheEvict가 모종의 이유로 제대로 작동 안할 …
> 게시글 조회 성능 개선(heap 메모리 사용량 줄이기, 첫 조회에 대하여 캐싱 적용)

- src/main/java/com/bbangle/bbangle/board/repository/util/BoardPageGenerator.java
- src/main/java/com/bbangle/bbangle/page/CursorPageResponse.java
- src/test/java/com/bbangle/bbangle/page/CursorPageResponseTest.java
- 공통 커서 페이지를 구현
service 코드에서  아래와 같이 호출하면 됩니다
`CursorPageResponse.of(memberBookResponses, PAGE_SIZE, MemberBookResponse::getMemberBookId)`
> 공통 커서 페이지 구현

- src/main/java/com/bbangle/bbangle/board/controller/RandomBoardController.java
- src/main/java/com/bbangle/bbangle/board/domain/RandomBoard.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/RandomBoardRepository.java
- src/main/java/com/bbangle/bbangle/board/service/RandomBoardService.java
- src/main/java/com/bbangle/bbangle/config/RedisConfig.java
- src/main/java/com/bbangle/bbangle/exception/BbangleErrorCode.java
- src/main/java/com/bbangle/bbangle/redis/RedisService.java
- src/main/java/com/bbangle/bbangle/wishlist/validator/WishListFolderValidator.java
---
assignees: ''
---
- 폴더 이름 수정 시 기본 폴더를 수정 못하게는 막아놨지만 다른 폴더 이름을 기본 폴더로 변경이 가능한 상황 발생
- 기본 폴더 라는 이름을 사용하지 못하게 validation 추가
- 랜덤 게시글 내려주는 API 추가
> 위시리스트 폴더 이름 변경 시 '기본 폴더'로 변경하지 못하게 로직 수정, 랜덤 API 추가

- src/main/java/com/bbangle/bbangle/exception/BbangleErrorCode.java
- src/main/java/com/bbangle/bbangle/review/controller/ReviewController.java
- src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
- src/main/java/com/bbangle/bbangle/wishlist/validator/WishListFolderValidator.java
---
assignees: ''
---
- 도움돼요를 누를 때 이미 도움돼요를 누른 내용인지 확인하지 못해 예외가 발생
- DB에 한 리뷰에 대해 한 사람이 여러 번 도움돼요를 누른 것으로 기록이 됨
- 로직 상 한 사람 한 리뷰에 대하여 하나의 도움돼요만을 누를 수 있어야 함
- 여러 개의 도움돼요를 눌러 쿼리 상 도움 돼요 하나만 조회되어야 하는 로직에 여러 개가 검색되어 쿼리 Exception이 발생
- 리뷰 도움돼요를 누를 때 이미 도움돼요를 누른 리뷰인지 확인하는 로직 추가
``` java
@Transactional
public void insertLike(Long reviewId, Long memberId) {
reviewLikeRepository.findByMemberIdAndReviewId(memberId, reviewId)
.ifPresent(reviewLike -> {
throw new BbangleException(BbangleErrorCode.REVIEW_ALREADY_LIKED);
});
reviewLikeRepository.save(ReviewLike.builder()
.memberId(memberId)
.reviewId(reviewId)
.build());
}
```
- 추가로 리뷰 도움돼요를 누르는 API가 GET 요청으로 되어 있어 POST 요청으로 변경
- 도움돼요를 두 번 누를 시 예외처리가 되는 것 확인
> 리뷰 좋아요를 누를 시 이미 좋아요를 눌렀는지 확인하는 로직 추가

- src/main/java/com/bbangle/bbangle/board/controller/BoardDetailController.java
- src/main/java/com/bbangle/bbangle/board/domain/RecommendationSimilarBoard.java
- src/main/java/com/bbangle/bbangle/board/domain/SimilarityModelVerEnum.java
- src/main/java/com/bbangle/bbangle/board/domain/SimilarityTypeEnum.java
- src/main/java/com/bbangle/bbangle/board/domain/composityKey/RecommendationSimilarBoardComposityKey.java
- src/main/java/com/bbangle/bbangle/board/dto/BoardInfo.java
- src/main/java/com/bbangle/bbangle/board/dto/SimilarityBoardDto.java
- src/main/java/com/bbangle/bbangle/board/dto/SimilarityBoardResponse.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardDetailQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/repository/RecommendationSimilarBoardRepository.java
- src/main/java/com/bbangle/bbangle/board/service/BoardDetailService.java
- src/main/java/com/bbangle/bbangle/common/domain/CreatedAtBaseEntity.java
- src/test/java/com/bbangle/bbangle/AbstractIntegrationTest.java
- src/test/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryTest.java
- src/test/java/com/bbangle/bbangle/fixture/RecommendationSimilarBoardFixture.java
---
assignees: ''
---
https://github.com/eco-dessert-platform/backend/issues/302
- 요청된 boardId 정보를 recommendation_similar_board 테이블에서 recommend_item(추천 상품)을 가져옴(추천 상품 3개)
- board, product, boardStatistic, wishlist 조인
- 옵티마이저에 의해 효율적으로 인덱스 타는 것을 확인
- 위 데이터를 묶음 상품, 품절 유무, 찜 여부 등을 가공하여 새로운 DTO에 담아서 프론트에 전달 
- fixtureMonkey 에러인 것 같음
- 다소 급하게 진행 되다보니, 코드 개선은 이후 진행해야할 것 같습니다.
- 양해 부탁드립니다!
- 구현하고 있는 화면은 아래 화면 입니다.
> 🚀 유사도 측정한 추천 상품 조회 구현

- src/main/java/com/bbangle/bbangle/boardstatistic/repository/BoardStatisticRepository.java
- src/main/java/com/bbangle/bbangle/review/dto/ReviewDto.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
- src/main/java/com/bbangle/bbangle/review/service/ReviewStatistics.java
- src/test/java/com/bbangle/bbangle/review/service/ReviewServiceTest.java
---
assignees: ''
---
https://github.com/eco-dessert-platform/backend/issues/306
+
- 이전엔 뱃지가 없다면 "긍정적인 뱃지" 출력에서 화면 표시 안하는 것으로 변경
- ex)  맛 뱃지의 대한 리뷰가 없다면 기존엔 "GOOD"을 내려줌, 하지만 지금은 없으면 안내려줌
- "NULL" 값 추가로 기존 로직에서 최적화 해 놓은 방식을 사용할 수 없게 됨
- 뱃지 계산 로직 변경
- "NULL" 값일 경우 필터링
- 리뷰 평균 점수 계산 로직 변경 
- 기존 방식은 리뷰 전체를 가져와 평균을 계산
- 현재는 board_statistics 테이블에 계산돼 있는 리뷰 평균을 가져옴
- FixtureMonkey 수정 필요...
> 🐛 상세페이지 > 상품탭 > 리뷰 뱃지에서 "부드러워요"만 출력되는 버그 수정 완료

- src/main/java/com/bbangle/bbangle/review/dto/ReviewBadgeDto.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
- src/main/java/com/bbangle/bbangle/review/service/ReviewStatistics.java
---
assignees: ''
---
**공통 메서드 사용**
- findByBoardId 메서드를 여러 곳에서 공통으로 사용 중이었음.
- 이를 모르고 사용하다가, 해당 필드를 삭제하고 rate 필드를 제거했더니 예상치 못한 곳에서 버그가 발생. (에러는 발생하지 않았으나, rate 값이 누락되어 결과에 반영되지 않는 문제가 생김)
- 기존 findByBoardId를 원래 상태로 복구한 뒤, 뱃지 데이터를 가져오는 새로운 메서드 findReviewBadgeByBoardId를 생성하여 문제를 해결.
**공통 DTO 사용**
- 기존에 ReviewDto를 사용 중이었으며, 해당 DTO는 리뷰와 관련된 거의 모든 필드를 포함하고 있었음.
- 단순히 뱃지 데이터만 필요한 상황에서도 이를 사용하다 보니, DTO가 여러 용도로 활용되면서 혼란이 발생.
- 이를 해결하기 위해 ReviewBadgeDto를 새로 생성하여, 뱃지 데이터만 포함하는 명확한 DTO를 도입.
- findByBoardId 메서드 원상 복구
- findReviewBadgeByBoardId 뱃지를 가져오는 새로운 메서드 생성
- ReviewBadgeDto 클래스 생성
> Badge Repository Method 변경

- src/main/java/com/bbangle/bbangle/board/service/BoardDetailService.java
- src/main/java/com/bbangle/bbangle/boardstatistic/repository/BoardStatisticRepositoryImpl.java
---
assignees: ''
---
- 인기 검색을 셔플하는 과정에서 에러발생
- 셔플하는 리스트가 정적 리스트라 에러 발생
- 정적 리스트에서 동적 리스트로 변경
- 서브쿼리에서 Limit이 안되는 버그가 있어 쿼리 분할
> ✅ 정적메서드로 인해 발생하는 에러 수정 및 인기 상품 가져오는 쿼리 수정

- src/main/java/com/bbangle/bbangle/wishlist/domain/WishListBoard.java
- src/main/java/com/bbangle/bbangle/wishlist/repository/WishListFolderRepository.java
- src/main/java/com/bbangle/bbangle/wishlist/service/WishListBoardService.java
- src/main/java/com/bbangle/bbangle/wishlist/service/WishListFolderService.java
- src/test/java/com/bbangle/bbangle/wishlist/service/WishListBoardServiceTest.java
---
assignees: ''
---
* Resolves #322 
- 한 유저가 한 개의 게시글을 두 번 찜할 수 없는 정책이 존재
- 그러나 위 사진의 로직 상 찜을 누르는 POST 요청이 커밋되기 전에 Validation 로직에서 DB에 존재하는지 확인하는 로직을 실행할 경우 한 유저가 한 게시글에 대해 두 번 찜한 데이터가 기록되는 문제가 발생
- 이를 해결하기 위해 NamedLock, 분산락, 유티크 제약 조건을 생각
- NamedLock의 경우, boardId, memberId를 기준으로 DB에 락을 걸고 로직이 끝날 때 락을 반납하는 식으로 구현 가능
`E.g. String lockName = "wishBoard:" + memberId + ":" + boardId;`
- 분산락도 비슷한 개념으로 락을 걸고 로직이 끝날 시 획득 가능
- unique 제약 조건의 경우 이미 DB에 데이터가 존재하는 경우 예외가 발생하게 만드는 것
- unique 제약 조건만을 거는 방식을 채택
validation 조회 로직이 사라지기 때문
-> 기존에는 DB에 데이터가 있는지 없는지 로직을 쿼리로 날려서 확인하였다.
그러나 unique 제약 조건을 거는 경우 DB에 조회해서 데이터가 있을 시 반드시 예외가 발생한다
그렇기에 원래 로직이 아래와 같았다면
```
select ... (존재하는지 확인하는 조회 로직)
insert ...(존재하지 않는다는 검증 후 데이터 …
```
> 위시리스트에 게시글 추가할 시 발생하는 동시성 문제 제어

- .gitignore
- build.gradle
1. sql 파일 경로는 "resources/docker/mariadb/db_dump"로 지정해주세요.
- ![image](https://github.com/user-attachments/assets/58f3d649-2404-41b1-a0b2-a23e3ebc32e1)
- 도커 파일은 빵그리 docker Repository에 있습니다.
2. 노션에서 yml을 받아주세요.
**사용방법**
- Docker Repository에 있는 폴더를 src/main/resources에 clone해주세요.
- 도커 컴포즈 해서 MariaDB 컨테이너 띄워주세요.
- 서버를 실행해주세요.
> 🚀 Flyway 적용

- src/main/java/com/bbangle/bbangle/board/domain/BoardDetail.java
- src/main/java/com/bbangle/bbangle/board/dto/BoardImageDetailResponse.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardDetailQueryDSLRepository.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/service/BoardDetailService.java
- src/main/java/com/bbangle/bbangle/util/HtmlUtils.java
- src/test/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryTest.java
- src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
- src/test/java/com/bbangle/bbangle/search/service/SearchServiceTest.java
- src/test/java/com/bbangle/bbangle/store/repository/StoreRepositoryTest.java
- src/test/java/com/bbangle/bbangle/util/HtmlUtilsTest.java
close #361 
**Before:**
**After:**
> [Refactor] 보드 상세페이지 이미지 저장 방식 변경 

- src/main/java/com/bbangle/bbangle/board/domain/Board.java
- src/main/java/com/bbangle/bbangle/board/domain/ProductImg.java
- src/main/java/com/bbangle/bbangle/board/dto/BoardAndImageDto.java
- src/main/java/com/bbangle/bbangle/board/dto/BoardAndImageResponses.java
- src/main/java/com/bbangle/bbangle/board/dto/BoardImageDetailResponse.java
- src/main/java/com/bbangle/bbangle/board/dto/BoardInfoDto.java
- src/main/java/com/bbangle/bbangle/board/recommend/repository/RecommendBoardQueryDSLRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardRepository.java
- src/main/java/com/bbangle/bbangle/board/repository/BoardRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/query/HighPriceBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/query/HighRatedBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/query/LowPriceBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/query/MostReviewedBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/query/MostWishedBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/query/PreferenceRecommendBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/query/RecentBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/board/repository/basic/query/RecommendBoardQueryProviderResolver.java
- src/main/java/com/bbangle/bbangle/board/repository/folder/query/LowPriceBoardQueryProvider.java
- src/main/java/com/bbangle/bbangle/board/repository/folder/query/PopularBoardQueryProvider.java
- src/main/java/com/bbangle/bbangle/board/repository/folder/query/WishListRecentBoardQueryProvider.java
- src/main/java/com/bbangle/bbangle/board/service/BoardDetailService.java
- src/main/java/com/bbangle/bbangle/exception/BbangleErrorCode.java
- src/main/java/com/bbangle/bbangle/push/repository/PushQueryDSLRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/search/dto/SearchBoardResponseDto.java
- src/main/java/com/bbangle/bbangle/wishlist/repository/impl/WishListFolderRepositoryImpl.java
**문제점**
- 대표 썸네일은 board.profile에
- 나머지 썸네일은 prodct_img 테이블에
- 위 방식은 이미지를 한  테이블에 관리하지 않아 데이터 관리 및 개발 복잡성이 늘어남
- `product_img`에는 대표 썸네일이 없고, `board.profile`에는 일반 썸네일이 없음. 데이터를 조작할 때 일관성을 유지하기 어려움.
**개선 방향**
- board.profile을 없애고
- product_img 테이블에 상품 이미지(상품 상세 페이지 이미지 x)들을 모두 저장
**개선 후 **
- 20여개 쿼리문 변경(board.profile → product_img.url  join product_img on img_index = 0으로)
**문제점**
- BoardDetailService.getBoardDtos() 함수에서 쿼리 반환값인 DTO에서 최종 Response로 변하는 과정이 직관적이지 않음
**개선 결과물 과정**
1. BoardDTOS -> BoardResponses
- 위 과정에서 썸네일과 썸네일 아닌 이미지 구분
- 서비스 코드에서는 이과정을 몰라도 됨
2. Responses와 다른 부가적인 정보들(위시리스트유무, 상세페이지 내용)을 합쳐서 최종 Response로 만듬
---
pr 보실 때 파일 양이 많아 커밋 별로 나눠서 보시는 것을 추천합니다
> [Refactor] Board 이미지 테이블 리팩토링: ERD 개선 및 데이터 일관성 강화

- build.gradle
- src/main/java/com/bbangle/bbangle/common/querylistener/CustomQueryLoggingListener.java
- src/main/java/com/bbangle/bbangle/common/querylistener/QueryTimerContext.java
- src/main/java/com/bbangle/bbangle/common/service/RequestTimeInterceptor.java
- src/main/java/com/bbangle/bbangle/config/DataSourceProxyConfig.java
* **요청 단위 처리시간 측정 기능 추가**
* `RequestTimeInterceptor`를 통해 HTTP 요청 시작 시점부터 종료까지의 시간을 측정
* DB 쿼리 수행 시간을 합산한 `QueryTimerContext` 정보를 함께 로그로 출력
* 슬랙 알림 메세지 수정
* **Datasource-proxy 도입**
* `net.ttddyy:datasource-proxy` 라이브러리를 도입하여 JDBC 쿼리 실행 시간 측정 및 로깅
* `CustomQueryLoggingListener`를 통해 쿼리문, 파라미터, 성공 여부, 소요 시간 등을 debug 로그로 출력
* 쿼리 수행 시간은 `QueryTimerContext`에 누적되어 인터셉터에서 총 DB 처리 시간으로 활용됨
* **DataSource 프록시 설정**
* `DataSourceProxyConfig`에서 `HikariDataSource`를 감싼 `ProxyDataSource`를 생성
* 테스트 환경(`!test`) 제외
---
```
- API           : GET /api/v1/board
- 총 DB 처리 시간 : 1850 ms
- 총 처리시간     : 3623 ms
```
쿼리별 debug 로그 예시:
```
- 쿼리문      : SELECT * FROM board WHERE id = ?
- 쿼리파라미터 : [[123]]
- 성공여부    : true
- 처리시간    : 87ms
```
---
* 추후 슬로우 쿼리 기준을 설정해 별도 추적하거나, 특정 경로 필터링도 가능
* 테스트 환경 제외
---
> 쿼리 처리시간 측정 및 로깅 기능 추가

- src/main/java/com/bbangle/bbangle/wishlist/repository/sort/strategy/RecentBoardInFolderSortRepository.java
> [Fix] 위시리스트 최근순 조회 조인 누락 수정

- src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
- src/main/java/com/bbangle/bbangle/board/facade/BoardFacade.java
- src/main/java/com/bbangle/bbangle/search/controller/SearchController.java
- src/main/java/com/bbangle/bbangle/search/controller/mapper/SearchMapper.java
- src/main/java/com/bbangle/bbangle/search/repository/SearchRepositoryImpl.java
- src/main/java/com/bbangle/bbangle/search/service/SearchService.java
- src/main/java/com/bbangle/bbangle/search/service/dto/SearchCommand.java
- src/main/java/com/bbangle/bbangle/search/service/dto/SearchInfo.java
- src/main/java/com/bbangle/bbangle/search/service/mapper/SearchInfoMapper.java
**변경 배경**
- 기존 10개 단위 제한으로 인해 백엔드 요청이 과도하게 발생함
- API 호출 속도가 느린 상황에서 자주 호출되면서 성능 저하가 심화됨
- 이를 완화하기 위해 기본 조회 개수를 30개로 확장하여 요청 빈도 감소
**주요 변경 사항**
- 기존의 BOARD_PAGE_SIZE_PLUS_ONE = 11에서 동적으로 command.limitSize() + 1을 적용
- 프론트 기본 요청 limit을 30로 설정하여 실제 화면에 노출
> 게시글 조회 기본 제한 값 변경

- src/main/java/com/bbangle/bbangle/wishlist/repository/WishListFolderRepositoryImpl.java
- inner join으로서 상품이미지가 없으면 조회가 안됐습니다.
- left join으로 오류 수정
> [Fix] 위시리스트 조회 이미지와 left join으로 수정

- src/main/java/com/bbangle/bbangle/member/domain/Member.java
- src/main/java/com/bbangle/bbangle/member/service/ProfileServiceImpl.java
- 프로필 삭제 후 수정 시 프로필 삭제가 안되고 있음
- else문 추가로 이미지에 대한 내용이 없을 경우 null 처리
> 프로필 삭제 에러 수정

- src/main/java/com/bbangle/bbangle/member/dto/MemberIdWithRoleDto.java
- projection  DTO 클래스 생성자 접근제어자 수정 `private` => `public`
에러 로그 
```
No constructor found for class com.bbangle.bbangle.member.dto.MemberIdWithRoleDto with parameters: [class java.lang.Long, class com.bbangle.bbangle...
- url: /api/v1/oauth/login/kakao
- 위치: com.bbangle.bbangle.member.repository.MemberRepositoryImpl, findByProviderAndProviderId
- message: No constructor found for class com.bbangle.bbangle.member.dto.MemberIdWithRoleDto with parameters: [class java.lang.Long, class com.bbangle.bbangle.member.domain.Role]
```
> [Fix] No constructor found ERROR 수정  

- src/main/java/com/bbangle/bbangle/preference/domain/PreferenceType.java
프론트에서 선호도 수정 요청 시 `해당없음`에 대한 항목이 필요해서 해당 요청에 대해 대응하기 위해 `Preference Type`에 `NONE` 항목을 추가함. 
@yunyechan9893 
`board_preferece_staticis` 생성하는 로직에서 NONE 인 경우 선호도 스코어를 0으로 처리하면 될까요?
> [Fix] PreferenceType.NONE 추가로  프론트 요청 대응

- src/main/resources/flyway/V20__app.sql
- product_board 테이블에서 참조 중인 product_detail.id가 존재하지 않는 경우, 해당 board_detail_id 값을 NULL로 업데이트하는 SQL 스크립트를 추가합니다.
- product_board.board_detail_id가 product_detail.id를 참조하지만, 일부 값이 존재하지 않는 데이터로 남아 있음.
- 데이터 무결성을 유지하고, 향후 조인 시 오류를 방지하기 위해 해당 컬럼을 NULL로 정리.
> 📝 Pull Request: NULL 처리된 board_detail_id 정리

- src/test/java/com/bbangle/bbangle/board/repository/BoardRepositoryCursorTest.java
- src/test/java/com/bbangle/bbangle/board/repository/BoardRepositoryTest.java
- src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
- src/test/java/com/bbangle/bbangle/board/service/BoardUploadServiceTest.java
- src/test/java/com/bbangle/bbangle/common/adaptor/slack/TestSlackAdaptorConfig.java
- src/test/java/com/bbangle/bbangle/common/page/NotificationCustomPageTest.java
- src/test/java/com/bbangle/bbangle/config/JsonDataEncoder.java
- src/test/java/com/bbangle/bbangle/configuration/TokenGenerator.java
- src/test/java/com/bbangle/bbangle/fixture/NoticeFixture.java
- src/test/java/com/bbangle/bbangle/notification/controller/NotificationControllerSliceTest.java
- src/test/java/com/bbangle/bbangle/notification/repository/NotificationRepositoryTest.java
- src/test/java/com/bbangle/bbangle/notification/service/NotificationServiceTest.java
- src/test/java/com/bbangle/bbangle/preference/service/PreferenceServiceTest.java
- src/test/java/com/bbangle/bbangle/push/controller/PushControllerTest.java
- src/test/java/com/bbangle/bbangle/push/service/PushServiceTest.java
- src/test/java/com/bbangle/bbangle/token/jwt/TestJwtPropertiesConfig.java
- src/test/java/com/bbangle/bbangle/wishlist/controller/WishListStoreControllerTest.java
- src/test/java/com/bbangle/bbangle/wishlist/service/WishListBoardServiceTest.java
- src/test/java/com/bbangle/bbangle/wishlist/service/WishListFolderServiceTest.java
현재 테스트 코드 관리가 미흡하여, v1.2 개발에 앞서 테스트 코드 컨벤션과 구조를 통일하면 좋을 것 같습니다.
제가 공부해본 내용을 바탕으로 `Notification` 기능 관련해서 테스트 코드를 작성해보았습니다.
작성하다보니 내용이 많이 길어졌네요..
천천히 확인 해보시고 틀린 부분이나 더 좋은 의견  있으시면 편하게 말씀해주세요~~!
테스트는 크게 `Controller`, `Service(비즈니스 로직)`,  `Repository`각 계층별로 단위 테스트 또는 슬라이스 테스트를 작성했습니다.
계층과 별개로 모든 테스트는 `given_when_then` 패턴을 적용하여 작성했습니다.
---
기존 `@SpringBootTest`를 사용한 통합테스트 구조에서 `@WebMvcTest`를 사용하여 테스트 경량화
- `@SpringBootTest`는 spring 실행에 필요한 모든 컨텍스트를 로드에서 성능 부담이 있습니다.
- `@WebMvcTest`를 사용하여 Controller 계층과 관련된 `SecurityFilter`, `GlobalControllerAdvice` 등 필요한 빈 또는 컴포넌트만 로드해서 사용하여 비교적 성능에 부담이 적습니다.
- 만약 main 코드의 복잡한 의존관계로 인해 bean을 찾지 못하는 경우가 발생할 수 있습니다. 이런경우 `@TestConfiguration`, `@TestComponent`를 통해 테스트 용 빈을 정의하여 `@Import` 어노테이션을 통해 의존 문제를 해결할 수 있습니다. => 다른 계층 테스트에서도 사용되는 개념입니다.
- `@SpyBean`, …
> [Refactor] Notification 테스트코드 리팩토링 및 구조 개선

- build.gradle
- 연관된 이슈: Closes #418
- 테스트코드에서 롬복 어노테이션을 인식하지 못하는 문제 해결
- `testCompileOnly` / `testAnnotationProcessor` 의존성 추가
> [Fix] 테스트 소스에 Lombok annotation processor 적용

- src/main/java/com/bbangle/bbangle/token/oauth/OauthController.java
- src/main/java/com/bbangle/bbangle/token/oauth/infra/kakao/dto/LoginTokenResponse.java
- src/main/java/com/bbangle/bbangle/token/swagger/OauthApi.java
연관된 이슈: #421 
- 내용 
카카오/구글 oauth 를 이용한 로그인 api이고 
기존 member 와 uri 분리해서 요청/응답 값 동일하게 설계 했습니다.
- 요청[REQUEST]  `GET /api/v1/oauth/seller/login/{oauthServerType}`
`oauthServerType` : KAKAO or GOOGLE
`token` : Bearer 토큰
- 응답[RESPONSE]
`refreshToken` : 리프레시 토큰
`accessToken` : 액세스 토큰
기존에 사용하는 member의 oauth 로그인 url 수정할수 있으면 컨트롤러 창구 하나에서 받고 
RequestParam 으로 seller, member 구분해서 받은 후 서비스에서 분기 처리하는것도 좋을것 같습니다.
ex) /api/v1/oauth/{userRole}/login/{oauthServerType}
> 판매자 로그인 API 설계 (브랜치 변경)
